apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: n63t54ifa-nodejs
  janus-idp.io/tekton: n63t54ifa-nodejs
  backstage.io/kubernetes-id: n63t54ifa-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: n63t54ifa-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
